window.HIKARI_DATA={
 "hero": {
  "id": 113415,
  "title": "JUJUTSU KAISEN",
  "native": "呪術廻戦",
  "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-LHBAeoZDIsnF.jpg",
  "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg",
  "color": "#e45d5d",
  "score": 84,
  "year": 2020,
  "format": "TV",
  "status": "FINISHED",
  "genres": [
   "Action",
   "Drama",
   "Supernatural"
  ],
  "episodes": 24,
  "studio": "MAPPA",
  "dub": true,
  "sources": [],
  "watched": 0,
  "desc": "A boy fights... for \"the right death.\" Hardship, regret, shame: the negative feelings that humans feel become Curses that lurk in our everyday lives. The Curses run rampant throughout the world, capable of leading people to terrible misfortune and even death. What's more, the Curses can only be exorcised by another Curse. Itadori Yuji is "
 },
 "grid": [
  {
   "id": 184951,
   "title": "You and I Are Polar Opposites",
   "native": "正反対な君と僕",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx184951-s8Lg2muPBhdX.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/184951-Rx1mZZfKa9IU.jpg",
   "color": "#e4a135",
   "score": 83,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance",
    "Slice of Life"
   ],
   "episodes": 12,
   "studio": "Lapin Track",
   "dub": true,
   "sources": [],
   "watched": 0,
   "fav": true
  },
  {
   "id": 169580,
   "title": "I Made Friends with the Second Prettiest Girl in My Class",
   "native": "クラスで２番目に可愛い女の子と友だちになった",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx169580-nXxpmqu6UVux.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/169580-RUdWWw0j74HH.jpg",
   "color": "#f1bb50",
   "score": 80,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance"
   ],
   "episodes": 12,
   "studio": "CONNECT",
   "dub": false,
   "sources": [],
   "watched": 0
  },
  {
   "id": 199547,
   "title": "MARRIAGETOXIN",
   "native": "マリッジトキシン",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx199547-LAaG3cmKCGhr.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/199547-7230SVo56b42.jpg",
   "color": "#1ae4f1",
   "score": 76,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Comedy",
    "Drama"
   ],
   "episodes": 13,
   "studio": "bones film",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 189987,
   "title": "The Klutzy Class Monitor and the Girl with the Short Skirt",
   "native": "ポンコツ風紀委員とスカート丈が不適切なJKの話",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx189987-CkTDPfD7vu2Y.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/189987-0UGf5F7zWNvv.jpg",
   "color": "#e4c950",
   "score": 76,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance",
    "Slice of Life"
   ],
   "episodes": 12,
   "studio": "Zero-G",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 194393,
   "title": "I Want to End this Love Game",
   "native": "愛してるゲームを終わらせたい",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx194393-0H9yYABu6y0i.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/194393-FmUDMgF0apUJ.jpg",
   "color": "#43aef1",
   "score": 75,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance",
    "Slice of Life"
   ],
   "episodes": 12,
   "studio": "Felix Film",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 187942,
   "title": "Tune In to the Midnight Heart",
   "native": "真夜中ハートチューン",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx187942-c2cZvunJGfiE.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/187942-tUpZo1VxashN.jpg",
   "color": "#e4a150",
   "score": 73,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance"
   ],
   "episodes": 12,
   "studio": "Gekkou",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 187538,
   "title": "BLACK TORCH",
   "native": "BLACK TORCH",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx187538-fXVXKYUA3VV6.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/187538-287evzCezNl0.jpg",
   "color": "#435dff",
   "score": 72,
   "year": 2026,
   "format": "TV",
   "status": "RELEASING",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 0,
   "studio": "100studio",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 190704,
   "title": "Mistress Kanan is Devilishly Easy",
   "native": "カナン様はあくまでチョロい",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx190704-Ts1VvkrNdnCZ.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/190704-bLXpyNFVZbss.jpg",
   "color": "#3586ff",
   "score": 70,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Ecchi",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "Studio KAI",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 186744,
   "title": "Even a Replica Can Fall in Love",
   "native": "レプリカだって、恋をする",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx186744-nFH4y2slUrO4.jpg",
   "banner": "",
   "color": "#f1f1c9",
   "score": 69,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Drama",
    "Romance",
    "Supernatural"
   ],
   "episodes": 13,
   "studio": "Voil",
   "dub": false,
   "sources": [],
   "watched": 0
  },
  {
   "id": 199066,
   "title": "Hanaori-san Still Wants to Fight in the Next Life",
   "native": "花織さんは転生しても喧嘩がしたい",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx199066-YXDVsguvFZMm.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/199066-nmAYnI6uChse.jpg",
   "color": "#43bbe4",
   "score": 67,
   "year": 2026,
   "format": "TV",
   "status": "RELEASING",
   "genres": [
    "Comedy",
    "Romance",
    "Supernatural"
   ],
   "episodes": 0,
   "studio": "LIDENFILMS",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 189565,
   "title": "You Can't Be In a Rom-Com with Your Childhood Friends!",
   "native": "幼馴染とはラブコメにならない",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx189565-OHhadYSsd0Bg.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/189565-40afF0Vg7Lt8.jpg",
   "color": "#e4ae78",
   "score": 63,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance"
   ],
   "episodes": 12,
   "studio": "Tezuka Productions",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 202381,
   "title": "Killed again, Mr. Detective.",
   "native": "また殺されてしまったのですね、探偵様",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx202381-bxgyUXGtGtZj.jpg",
   "banner": "",
   "color": "#E8A34B",
   "score": 59,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Mystery",
    "Psychological",
    "Supernatural"
   ],
   "episodes": 12,
   "studio": "LIDENFILMS",
   "dub": false,
   "sources": [],
   "watched": 0
  },
  {
   "id": 178025,
   "title": "Gachiakuta",
   "native": "ガチアクタ",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178025-cWJKEsZynkil.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/178025-WvcXi1J2SGRa.jpg",
   "color": "#e4a150",
   "score": 82,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Drama",
    "Fantasy"
   ],
   "episodes": 24,
   "studio": "bones film",
   "dub": true,
   "sources": [],
   "watched": 0,
   "fav": true,
   "local": 12
  },
  {
   "id": 178886,
   "title": "Dealing with Mikadono Sisters Is a Breeze",
   "native": "帝乃三姉妹は案外、チョロい。",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178886-KjzSXyEB61zX.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/178886-wUxMvrfIuAfU.jpg",
   "color": "#f19343",
   "score": 76,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance"
   ],
   "episodes": 12,
   "studio": "P.A.WORKS",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 180082,
   "title": "Chitose Is in the Ramune Bottle",
   "native": "千歳くんはラムネ瓶のなか",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx180082-IZAlf06G2VVm.png",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/180082-EoMpR2lHsD73.jpg",
   "color": "#43aeff",
   "score": 73,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance"
   ],
   "episodes": 13,
   "studio": "feel.",
   "dub": false,
   "sources": [],
   "watched": 0
  },
  {
   "id": 143200,
   "title": "Summer Pockets",
   "native": "Summer Pockets",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143200-42OaDCS6VEy3.png",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143200-R0qpwS1C6b8i.jpg",
   "color": "#50bbf1",
   "score": 71,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Drama",
    "Romance",
    "Slice of Life"
   ],
   "episodes": 26,
   "studio": "feel.",
   "dub": false,
   "sources": [],
   "watched": 0
  },
  {
   "id": 186052,
   "title": "The Water Magician",
   "native": "水属性の魔法使い",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx186052-zq8h0Qo0O0sP.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/186052-SHiNjpnalGWy.jpg",
   "color": "#43d6e4",
   "score": 70,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "TYPHOON GRAPHICS",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 175872,
   "title": "The Brilliant Healer's New Life in the Shadows",
   "native": "一瞬で治療していたのに役立たずと追放された天才治癒師、闇ヒーラーとして楽しく生きる",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx175872-d55nfiC4WWHO.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/175872-Pb1aTEdwSIyh.jpg",
   "color": "#e47843",
   "score": 68,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Comedy",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "Makaria",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 186794,
   "title": "My Status as an Assassin Obviously Exceeds the Hero’s",
   "native": "暗殺者である俺のステータスが 勇者よりも明らかに強いのだが",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx186794-Ns8xWNdMdOxq.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/186794-4XQdl7f4yVPR.jpg",
   "color": "#4378e4",
   "score": 66,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "Sunrise",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 179689,
   "title": "Headhunted to Another World: From Salaryman to Big Four!",
   "native": "サラリーマンが異世界に行ったら四天王になった話",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx179689-kmlqdU3IbxeM.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/179689-pmEg73tCaoMP.jpg",
   "color": "#c9e4f1",
   "score": 65,
   "year": 2025,
   "format": "ONA",
   "status": "FINISHED",
   "genres": [
    "Adventure",
    "Comedy",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "GEEKTOYS",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 177552,
   "title": "Medaka Kuroiwa is Impervious to My Charms",
   "native": "黒岩メダカに私の可愛いが通じない",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx177552-7XiOf3dGXmNs.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/177552-iLWNEFS7t8HM.jpg",
   "color": "#e4a186",
   "score": 64,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Ecchi",
    "Romance"
   ],
   "episodes": 12,
   "studio": "SynergySP",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 169969,
   "title": "Hero Without a Class: Who Even Needs Skills?!",
   "native": "無職の英雄 別にスキルなんか要らなかったんだが",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx169969-SqCjoqYT4A6Z.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/169969-qzQFIm1ADpyN.jpg",
   "color": "#e4c9a1",
   "score": 62,
   "year": 2025,
   "format": "ONA",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Comedy"
   ],
   "episodes": 12,
   "studio": "studio A-CAT",
   "dub": false,
   "sources": [],
   "watched": 0
  },
  {
   "id": 183161,
   "title": "The Beginning After the End",
   "native": "最強の王様、二度目の人生は 何をする?",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx183161-5M054tuPmZJX.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/183161-L5X2veRcYJnh.jpg",
   "color": "#43aeff",
   "score": 60,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "studio A-CAT",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 171018,
   "title": "DAN DA DAN",
   "native": "ダンダダン",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-60q1B6GK2Ghb.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/171018-SpwPNAduszXl.jpg",
   "color": "#e47850",
   "score": 83,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Comedy",
    "Drama"
   ],
   "episodes": 12,
   "studio": "Science SARU",
   "dub": true,
   "sources": [],
   "watched": 0,
   "fav": true
  },
  {
   "id": 153288,
   "title": "Kaiju No. 8",
   "native": "怪獣８号",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx153288-25FBfFJzEQ5O.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/153288-JNsWuMPMAuJL.jpg",
   "color": "#f1e4ae",
   "score": 81,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Sci-Fi"
   ],
   "episodes": 12,
   "studio": "Production I.G",
   "dub": true,
   "sources": [],
   "watched": 0,
   "fav": true,
   "local": 12
  },
  {
   "id": 151807,
   "title": "Solo Leveling",
   "native": "俺だけレベルアップな件",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-it355ZgzquUd.png",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-37yfQA3ym8PA.jpg",
   "color": "#35bbf1",
   "score": 81,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "A-1 Pictures",
   "dub": true,
   "sources": [],
   "watched": 0,
   "local": 12
  },
  {
   "id": 164172,
   "title": "Tying the Knot with an Amagami Sister",
   "native": "甘神さんちの縁結び",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx164172-GY2aqItIuqtR.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/164172-ceuofxXerReI.jpg",
   "color": "#e47850",
   "score": 73,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Drama",
    "Ecchi"
   ],
   "episodes": 24,
   "studio": "Drive",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 156415,
   "title": "I Was Reincarnated as the 7th Prince so I Can Take My Time Perfecting My Magical Ability",
   "native": "転生したら第七王子だったので、気ままに魔術を極めます",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx156415-zwP9deA786S1.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/156415-9pgnWbRE3ERY.jpg",
   "color": "#50e493",
   "score": 73,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "Tsumugi Akita Anime Lab",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 156023,
   "title": "An Archdemon's Dilemma: How to Love Your Elf Bride",
   "native": "魔王の俺が奴隷エルフを嫁にしたんだが、どう愛でればいい？",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx156023-cY4NC8gCcAg7.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/156023-0LHytkAZy4mL.jpg",
   "color": "#50a1e4",
   "score": 73,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Fantasy",
    "Romance"
   ],
   "episodes": 12,
   "studio": "Brain's Base",
   "dub": true,
   "sources": [],
   "watched": 0
  },
  {
   "id": 158559,
   "title": "2.5 Dimensional Seduction",
   "native": "2.5次元の誘惑",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx158559-yCnnnedsSCie.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/158559-plsSIyvRIiOc.jpg",
   "color": "#e4a150",
   "score": 72,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Ecchi",
    "Romance"
   ],
   "episodes": 24,
   "studio": "J.C.STAFF",
   "dub": true,
   "sources": [],
   "watched": 0
  }
 ],
 "airing": [
  {
   "title": "BLACK TORCH",
   "native": "BLACK TORCH",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx187538-fXVXKYUA3VV6.jpg",
   "ep": 4,
   "at": 1784984400,
   "dub": true
  },
  {
   "title": "Hanaori-san Still Wants to Fight in the Next Life",
   "native": "花織さんは転生しても喧嘩がしたい",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx199066-YXDVsguvFZMm.jpg",
   "ep": 3,
   "at": 1784998800,
   "dub": true
  },
  {
   "title": "You and I Are Polar Opposites Season 2",
   "native": "正反対な君と僕 第2期",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx210031-TppgcHZh46LY.jpg",
   "ep": 4,
   "at": 1785052800,
   "dub": true
  },
  {
   "title": "The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You Season 3",
   "native": "君のことが大大大大大好きな100人の彼女 第3期",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx200637-QLR5uv9SbQ69.jpg",
   "ep": 4,
   "at": 1785072600,
   "dub": true
  },
  {
   "title": "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs Season 2",
   "native": "乙女ゲー世界はモブに厳しい世界です2",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx159309-wRfh9O1odrDJ.jpg",
   "ep": 3,
   "at": 1784730600,
   "dub": false
  },
  {
   "title": "Re:ZERO -Starting Life in Another World- Season 4",
   "native": "Re:ゼロから始める異世界生活 4th season",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx189046-yaHWtS5FII46.jpg",
   "ep": 12,
   "at": 1786539600,
   "dub": true
  },
  {
   "title": "Re:Zero kara Hajimeru Kyuukei Jikan (Break Time) 4th Season",
   "native": "Re:ゼロから始める休憩時間(ブレイクタイム) 4th Season",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx210687-H54G1bTwCBpV.jpg",
   "ep": 12,
   "at": 1786541400,
   "dub": false
  }
 ],
 "cw": [
  {
   "id": 184951,
   "title": "You and I Are Polar Opposites",
   "native": "正反対な君と僕",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx184951-s8Lg2muPBhdX.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/184951-Rx1mZZfKa9IU.jpg",
   "color": "#e4a135",
   "score": 83,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance",
    "Slice of Life"
   ],
   "episodes": 12,
   "studio": "Lapin Track",
   "dub": true,
   "sources": [],
   "watched": 5,
   "fav": true
  },
  {
   "id": 171018,
   "title": "DAN DA DAN",
   "native": "ダンダダン",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-60q1B6GK2Ghb.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/171018-SpwPNAduszXl.jpg",
   "color": "#e47850",
   "score": 83,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Comedy",
    "Drama"
   ],
   "episodes": 12,
   "studio": "Science SARU",
   "dub": true,
   "sources": [],
   "watched": 8,
   "fav": true
  },
  {
   "id": 178025,
   "title": "Gachiakuta",
   "native": "ガチアクタ",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178025-cWJKEsZynkil.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/178025-WvcXi1J2SGRa.jpg",
   "color": "#e4a150",
   "score": 82,
   "year": 2025,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Drama",
    "Fantasy"
   ],
   "episodes": 24,
   "studio": "bones film",
   "dub": true,
   "sources": [],
   "watched": 6,
   "fav": true,
   "local": 12
  },
  {
   "id": 153288,
   "title": "Kaiju No. 8",
   "native": "怪獣８号",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx153288-25FBfFJzEQ5O.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/153288-JNsWuMPMAuJL.jpg",
   "color": "#f1e4ae",
   "score": 81,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Sci-Fi"
   ],
   "episodes": 12,
   "studio": "Production I.G",
   "dub": true,
   "sources": [],
   "watched": 10,
   "fav": true,
   "local": 12
  },
  {
   "id": 151807,
   "title": "Solo Leveling",
   "native": "俺だけレベルアップな件",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-it355ZgzquUd.png",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-37yfQA3ym8PA.jpg",
   "color": "#35bbf1",
   "score": 81,
   "year": 2024,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Action",
    "Adventure",
    "Fantasy"
   ],
   "episodes": 12,
   "studio": "A-1 Pictures",
   "dub": true,
   "sources": [],
   "watched": 6,
   "local": 12
  },
  {
   "id": 169580,
   "title": "I Made Friends with the Second Prettiest Girl in My Class",
   "native": "クラスで２番目に可愛い女の子と友だちになった",
   "cover": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx169580-nXxpmqu6UVux.jpg",
   "banner": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/169580-RUdWWw0j74HH.jpg",
   "color": "#f1bb50",
   "score": 80,
   "year": 2026,
   "format": "TV",
   "status": "FINISHED",
   "genres": [
    "Comedy",
    "Romance"
   ],
   "episodes": 12,
   "studio": "CONNECT",
   "dub": false,
   "sources": [],
   "watched": 4
  }
 ],
 "stats": {
  "shows": 167,
  "eps": 2869,
  "watched": 49,
  "genres": 18
 }
};
